### ISSUE TITLE
Padding issue on slider homepage responsive - Tab and Mobile

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#1]
Bug - Padding issue on slider on homepage responsive
Exp - padding should be same on slider section on homepage.
Ref Link - https://drive.google.com/file/d/1O_87UPt-ufAt7sJlp2COONcn-D9zfvUJ/view

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
