### ISSUE TITLE
Star rating UI issue on product page

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#10]
Bug - Star rating on product page not aligned properly.
Exp - Star rating should be left aligned with all content.
Ref link -
- https://nimb.ws/zt3owd
- https://nimb.ws/zt3owd
- https://nimb.ws/t26TzW

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
