### ISSUE TITLE
Wishlist icon not showing on "You may also like" Section.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#12]
Bug - Wishlist icon not showing on "You may also like" Section.
Exp - Should show wishlist icon on product tile.
Ref Link - https://drive.google.com/file/d/1B-Yr7Vg3YimxLrFSVo_KAjCfUO-VCm4w/view

**Comment by ui-chandrashekhar** [comment]
Developer's Work

**Comment by devSuneel** [comment]
resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
