### ISSUE TITLE
Padding issue on product image slider section - Mobile

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#13]
Bug - padding not showing last image on slider. Mobile UI.
Exp - Need to add padding on product image slider.
Ref Link - https://drive.google.com/file/d/1TAJ2OWh9-Iizkn8-CXkeFed5dGZMrRMb/view

**Comment by ui-chandrashekhar** [comment]
Not Found

https://www.awesomescreenshot.com/video/8672833?key=f1508729a16c8f1a4ed56f290ac28638

**Comment by ankitcedcoss** [comment]
Bug Fixed
