### ISSUE TITLE
Collection and static page heading UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#15]
Bug - Collection and static page heading showing left aligned. 
Exp - Sugg - Can make all pages heading should show in center.
Ref Link - https://drive.google.com/file/d/1t-S8GZOiQA9v1LKYjCcrRMFUDyi9WyKS/view

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
