### ISSUE TITLE
Wishlist icon not showing on search page product grid

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#17]
Bug - Wishlist button not showing on search page when user searched any product.
Exp - Wishlist icon should show in product tile on search page.
Ref link - https://drive.google.com/file/d/16A4N9x-3t0muPjw8dYG_1D2aloqnn9bM/view

**Comment by ui-chandrashekhar** [comment]
Developer

**Comment by devSuneel** [comment]
resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
