### ISSUE TITLE
Header navigation dropdown button UI issue 

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#2]
Bug - Dropdown button UI looks sticked with border.
Exp - Need to shift dropdown button slightly left side.
Ref Link - https://nimb.ws/N9BInY

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
