### ISSUE TITLE
login page button missing on create account page.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#23]
Bug - Back to login page button not showing on create account page.
Exp - Add button for back to login page.
Ref Link - https://nimb.ws/eabim2

**Comment by devSuneel** [comment]
https://gf2ege83a8xg17wa-55458922585.shopifypreview.com

**Comment by ankitcedcoss** [comment]
Bug Fixed
