### ISSUE TITLE
Button UI issue on wishlist popup button UI issue. 

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#25]
Bug 1 - Button UI issue on wishlist popup.
Exp -  Button lable and UI need to fix. text should show in single line.
Ref Link - https://nimb.ws/z8PJRN

Bug 2 - Button icons not aligned on wishlist popup.
Exp - Need to align button icon.
Ref Link - https://nimb.ws/mIX0UF

**Comment by ui-ravishukla** [comment]
![image](https://user-images.githubusercontent.com/102217972/166187775-28797605-68ac-4cc4-8838-3dd3e2d490c9.png)
its already looking good pls check @ankitcedcoss

**Comment by ankitcedcoss** [comment]
Bug Not Fixed - Please check on 1920*1080 resolution.
- https://nimb.ws/ZnLVKj
- https://nimb.ws/tJo2uL

**Comment by ankitcedcoss** [comment]
Bug Fixed
