### ISSUE TITLE
Quickview button overlapping issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#3]
Bug - Quick view button overlapping on header when user scroll on page.
Exp - Quick view buton should not overlap on header.
Ref link - https://drive.google.com/file/d/1lTpxwZBag1K1J5WO2kjEI9W_GlyR_CFq/view

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
