### ISSUE TITLE
Collection page UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#4]
Bug - Heading text UI issue and content on page is left aligned and showing more spacings.
Exp -  Need to Increase heading text size on page and remove spacings from collections page and padding should be balanced on both end on page.
Ref Link - 
- https://drive.google.com/file/d/1KLCA1pk5cALiG2IfOyaY2uHCDi-iI8My/view
- https://drive.google.com/file/d/1Ews0RaK_cDndiUDnJDZ_plAhBJ9tM4bF/view

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
