### ISSUE TITLE
Sort dropdown UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#6]
Bug - Sort by dropdown option text overlapping issue.
Exp - Dropdown text should not overlap on arrow icon and on drawer need to create some space between text and arrow buttons.
Ref Links - 
- https://nimb.ws/nmAuDQ
- https://nimb.ws/6z740x

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
