### ISSUE TITLE
Product image thumbnail UI issue on desktop and responsive - Tab

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#8]
Bug - Product image thumbnail UI not aligned properly on desktop and tab UI.
Exp - Thumbnail images should be aligned properly on desktop and tab UI.
Ref Link - https://nimb.ws/RzkyoI
tab - https://nimb.ws/12vtFR

**Comment by ui-chandrashekhar** [comment]
Resolved for desktop view not feasible for tab

**Comment by ankitcedcoss** [comment]
Bug Fixed
