### ISSUE TITLE
Product page buttons and quantity section is misplaced.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#9]
Bug - Product page buttons and quantity section is misplaced.
Exp - Need to swap buttons on product page.
Ref Link - 
- https://nimb.ws/tYoR5A
- https://nimb.ws/T0GelF

**Comment by ui-chandrashekhar** [comment]
Developer's  Work

**Comment by devSuneel** [comment]
resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
